version: '3.8'

services:
  pingu:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: pingu
    restart: unless-stopped
    
    # Environment configuration
    environment:
      - NODE_ENV=production
      - LOG_TO_FILE=true
      - LOG_FILE_PATH=/app/logs/app.log
      - DATABASE_PATH=/app/data/pingu.db
    
    # Load environment variables from file
    env_file:
      - .env
    
    # Port mapping
    ports:
      - "3000:3000"  # Webhook server
      - "3001:3001"  # Health endpoints
    
    # Volume mounts for persistence
    volumes:
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
    
    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
